# Generated by Django 6.1.1 on 2026-10-04 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models



def backfill_project_managers(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    ProjectMember = apps.get_model('projects', 'ProjectMember')

    for project in Project.objects.all():
        ProjectMember.objects.get_or_create(
            project_id=project.pk,
            user_id=project.created_by_id,
            defaults={
                'role': 'PROJECT_MANAGER',
            },
        )


def reverse_backfill_project_managers(apps, schema_editor):
    # Intentionally left as a no-op.
    # We should not delete memberships that may have been
    # created after the migration was applied.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='issue_counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PROJECT_MANAGER', 'Project Manager'), ('TEAM_MEMBER', 'Team Member'), ('VIEWER', 'Viewer')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'user'), name='unique_project_member')],
            },
        ),
        migrations.RunPython(
            backfill_project_managers,
            reverse_code=reverse_backfill_project_managers,
        ),
    ]
