# Generated by Django 6.1.2 on 2026-10-10 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_issue_counter_projectmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('PROJECT_CREATED', 'Project created'), ('PROJECT_UPDATED', 'Project updated'), ('PROJECT_ARCHIVED', 'Project archived'), ('MEMBER_ADDED', 'Member added'), ('MEMBER_REMOVED', 'Member removed'), ('ROLE_CHANGED', 'Role changed'), ('ISSUE_CREATED', 'Issue created'), ('ISSUE_UPDATED', 'Issue updated'), ('ISSUE_ASSIGNED', 'Issue assigned'), ('ISSUE_UNASSIGNED', 'Issue unassigned'), ('ISSUE_STATUS_CHANGED', 'Issue status changed'), ('ISSUE_ARCHIVED', 'Issue archived')], max_length=30)),
                ('entity_type', models.CharField(choices=[('PROJECT', 'Project'), ('MEMBERSHIP', 'Membership'), ('ISSUE', 'Issue')], max_length=20)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='activity_project_created_idx'), models.Index(fields=['entity_type', 'entity_id', '-created_at'], name='activity_entity_created_idx')],
            },
        ),
    ]
