# Generated by Django 6.1.1 on 2026-10-04 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='issue',
            name='issue_assignee_idx',
        ),
    ]
