# Generated by Django 6.1.2 on 2026-10-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_remove_issue_issue_assignee_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
